### ISSUE TITLE
REQUIRE_2FA crash at every poll event

### ISSUE THREAD

**Issue by nickshanks347** [jannisko/findmy-traccar-bridge#4]
I have the bridge configured to poll once an hour, and when it does, it always fails with REQUIRE_2FA. I need to delete `account.json` and `persistent_data.json` to force the bridge to stay up (otherwise it crashes). This happens at each poll event.

This is the error:

```
bridge  | 2025-04-17 13:40:16.618 | INFO     | findmy_traccar_bridge.bridge:bridge:172 - Next Apple API polling in 3363 seconds (2025-04-17T14:36:19 UTC)
bridge  | Traceback (most recent call last):
bridge  |   File "/bridge/.venv/bin/findmy-traccar-bridge", line 10, in <module>
bridge  |     sys.exit(bridge())
bridge  |              ^^^^^^^^
bridge  |   File "/bridge/.venv/lib/python3.12/site-packages/findmy_traccar_bridge/bridge.py", line 214, in bridge
bridge  |     result = acc.fetch_last_reports(haystack_keys)
bridge  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
bridge  |   File "/bridge/.venv/lib/python3.12/site-packages/findmy/reports/account.py", line 1084, in fetch_last_reports
bridge  |     return self._evt_loop.run_until_complete(coro)
bridge  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
bridge  |   File "/usr/local/lib/python3.12/asyncio/base_events.py", line 691, in run_until_complete
bridge  |     return future.result()
bridge  |            ^^^^^^^^^^^^^^^
bridge  |   File "/bridge/.venv/lib/python3.12/site-packages/findmy/reports/account.py", line 693, in fetch_last_reports
bridge  |     return await self.fetch_reports(keys, start, end)
bridge  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
bridge  |   File "/bridge/.venv/lib/python3.12/site-packages/findmy/reports/account.py", line 655, in fetch_reports
bridge  |     return await self._reports.fetch_reports(
bridge  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
bridge  |   File "/bridge/.venv/lib/python3.12/site-packages/findmy/reports/reports.py", line 299, in fetch_reports
bridge  |     reports.extend(await self._fetch_reports(date_from, date_to, chunk))
bridge  |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
bridge  |   File "/bridge/.venv/lib/python3.12/site-packages/findmy/reports/reports.py", line 327, in _fetch_reports
bridge  |     data = await self._account.fetch_raw_reports(start_date, end_date, ids)
bridge  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
bridge  |   File "/bridge/.venv/lib/python3.12/site-packages/findmy/reports/account.py", line 601, in fetch_raw_reports
bridge  |     raise UnauthorizedError(msg)
bridge  | findmy.errors.UnauthorizedError: Unexpected login state after reauth: LoginState.REQUIRE_2FA. Please log in again.
```

**Comment by nickshanks347** [comment]
> I have the same issue

I figured it out. Can you send me your anisette compose file?

**Comment by tsipizic** [comment]
> > I have the same issue
> 
> I figured it out. Can you send me your anisette compose file?

```
  anisette:
    image: dadoum/anisette-v3-server
    restart: unless-stopped
    container_name: anisette
    volumes:
      - anisette_data:/home/Alcoholic/.config/anisette-v3/lib/
```

**Comment by nickshanks347** [comment]
> > > I have the same issue
> > 
> > 
> > I figured it out. Can you send me your anisette compose file?
> 
> ```
>   anisette:
>     image: dadoum/anisette-v3-server
>     restart: unless-stopped
>     container_name: anisette
>     volumes:
>       - anisette_data:/home/Alcoholic/.config/anisette-v3/lib/
> ```

```
  anisette:
    image: dadoum/anisette-v3-server
    restart: unless-stopped
    container_name: anisette
    volumes:
      - anisette_data:/home/Alcoholic/.config/anisette-v3/
```

There you go :)
